name: Build and deploy PHP app to Azure Web App - php-crud-ci

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Run composer install if composer.json exists
        run: |
          if [ -f "composer.json" ]; then
            composer validate --no-check-publish
            composer install --prefer-dist --no-progress
          else
            echo "composer.json not found. Skipping install."
          fi

      - name: Zip public directory for deployment
        run: cd public && zip -r ../release.zip .

      - name: Create empty zip to clear wwwroot
        run: zip -r empty.zip . -x "*"

      - name: Upload artifacts for deployment
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: |
            release.zip
            empty.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifacts from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Unzip artifacts
        run: |
          unzip empty.zip -d empty
          unzip release.zip -d release

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1A9AEDCC55254EDEB3C612C3BABEA919 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6696C4A689164977A7C9EB9A6EFCC2E0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_22A8D8E1343E4135B440D8DEC07AD184 }}

      - name: Clean wwwroot with empty zip
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'php-crud-ci'
          slot-name: 'Production'
          package: empty

      - name: Deploy real application
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'php-crud-ci'
          slot-name: 'Production'
          package: release
