name: Clean and Deploy PHP to Azure Web App - php-crud-ci

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Install composer dependencies
        run: |
          if [ -f "composer.json" ]; then
            composer install --prefer-dist --no-progress
          fi

      - name: Prepare ZIP from public folder
        run: cd public && zip -r ../app.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1A9AEDCC55254EDEB3C612C3BABEA919 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6696C4A689164977A7C9EB9A6EFCC2E0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_22A8D8E1343E4135B440D8DEC07AD184 }}

      - name: Clean wwwroot manually
        run: |
          mkdir empty
          cd empty
          zip -r ../empty.zip . || echo "Empty zip created"
        shell: bash

      - name: Deploy empty zip to clean site
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'php-crud-ci'
          package: empty.zip

      - name: Deploy actual app
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'php-crud-ci'
          package: app.zip
