name: Build, Push and Deploy PHP Docker App to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "hassanmagh" --password-stdin

      - name: Build Docker image
        run: docker build -t hassanmagh/php_crud_with_tests:latest .

      - name: Push Docker image to Docker Hub
        run: docker push hassanmagh/php_crud_with_tests:latest

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1A9AEDCC55254EDEB3C612C3BABEA919 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6696C4A689164977A7C9EB9A6EFCC2E0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_22A8D8E1343E4135B440D8DEC07AD184 }}

      - name: Deploy to Azure Web App (using Docker image)
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'php-crud-ci'
          images: 'hassanmagh/php_crud_with_tests:latest'
