name: Build and Deploy PHP CRUD App to Azure

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  AZURE_APP_NAME: php-crud-ci
  AZURE_RESOURCE_GROUP: testphp
  AZURE_KUDU_API: https://php-crud-ci.scm.azurewebsites.net/api/command

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Validate & Install Composer
        run: |
          if [ -f composer.json ]; then
            composer validate --no-check-publish
            composer install --prefer-dist --no-progress
          fi

      - name: Zip public/ folder
        run: cd public && zip -r ../release.zip .

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download release artifact
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Unzip for deployment
        run: unzip release.zip

      - name: Clean Azure wwwroot via Kudu API
        run: |
          curl -X POST "$AZURE_KUDU_API" \
            -u ${{ secrets.KUDU_USERNAME }}:${{ secrets.KUDU_PASSWORD }} \
            -H "Content-Type: application/json" \
            -d '{"command": "rm -rf /home/site/wwwroot/*"}'
        env:
          AZURE_KUDU_API: ${{ env.AZURE_KUDU_API }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1A9AEDCC55254EDEB3C612C3BABEA919 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6696C4A689164977A7C9EB9A6EFCC2E0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_22A8D8E1343E4135B440D8DEC07AD184 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_APP_NAME }}
          slot-name: 'Production'
          package: .
